spring:
  web:
   cors:
    origin: '*'
    credentials: false
    methods: '*'
   flow:
    period: 3
    limit: 4000
    block: 30
  mail:
    password: BEAGDULMBXDYOGGO
    username: zhennan996@163.com
    host: smtp.163.com
    port: 465
    protocol: smtp
    properties:
        mail:
          smtp:
            auth: true
            ssl:
              enable: true
            starttls:
              enable: true
  rabbitmq:
    addresses: 42.194.242.94
    port: 15672
    username: xzn
    password: Nruonan996
    virtual-host: /
    # 开启生产者确认机制 (新版本配置)
    publisher-confirm-type: correlated
    # 开启消息回退（无法路由到队列时触发）
    publisher-returns: true
    listener:
      simple:
        # 重试机制
        retry:
          enabled: true #是否开启消费者重试
          max-attempts: 3 #最大重试次数
          initial-interval: 4000ms #重试间隔时间（单位毫秒）
          max-interval: 12000ms #重试最大时间间隔（单位毫秒）
          multiplier: 2 #间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
  data:
    redis:
      host: 42.194.242.94
      port: 6379
      username: default
      password: nruonan
  security:
    jwt:
     expire: 24
     key: xznzzhxzn
     limit:
      base: 10
      upgrade: 300
      frequency: 30
    filter:
      order: -100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.194.242.94:13306/monitor?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/monitor
    username: root
    password: nruonan
  minio:
    endpoint: 'http://42.194.242.94:9000'
    username: 'minioadmin'
    password: 'minioadmin'
  weather:
    key: 7554413210914257a74e8a1fddc1931f
server:
  port: 8081


